upload_max_filesize = 64M
post_max_size = 64M
max_execution_time = 60
memory_limit = 256M
date.timezone = Asia/Ho_Chi_Minh

; Production: hide errors
display_errors = Off
display_startup_errors = Off
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
log_errors = On
error_log = /var/log/php/error.log

; Security
expose_php = Off
session.cookie_httponly = 1
session.cookie_secure = 1
session.use_strict_mode = 1
