[www]
user = www-data
group = www-data

listen = 0.0.0.0:9000

pm = static
pm.max_children = 50
pm.max_requests = 1000

; Slow log for debugging performance
slowlog = /var/log/php/slow.log
request_slowlog_timeout = 5s
request_terminate_timeout = 60s

clear_env = no
